version: '3.8'

networks:
  mynetwork:  

services:
  app:
    build: .
    ports:
      - "8000:8000"
    working_dir: /app/src 
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SUPABASE_URL=${SUPABASE_URL}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - mynetwork  

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork 